### PR TITLE
Set width/height from client values if missing

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Set width/height from client values if missing

Allows image to be responsive

## Motivation and Context
Playlist Epic

## How Has This Been Tested?
Tested locally. Will update test coverage and fix any issues in subsequent PRs.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc fyi, this is the fix I was talking about for responsiveness. To confirm, the image has to be set to be non-responsive for this to work. Thanks!

**Comment by alex-deaconu** [comment]
@stulees @olegrise we found that images do not really resize to the container size correctly with `responsive=true`, so for the purposes of the `playlist` component they were not filling the area. This fix basically uses the `sizing=contain` mode, but sets the width/height if they are missing based on the container size. It works for the purpose and is backwards compatible with any existing image components.

Please review. Thanks!

**Review by stulees — APPROVED** [review]
@alex-deaconu Looks good to me

**Comment by stulees** [comment]
@alex-deaconu Actually, can you please bump the version of the component in `package.json`? Thanks

**Comment by alex-deaconu** [comment]
@stulees updated, thanks!

**Comment by stulees** [comment]
@alex-deaconu thanks!

**Comment by alex-deaconu** [comment]
@mmeiers @osmankarame you may be interested in this as well. Just to summarize, when not using `responsive=true`, and using `sizing=contain` the image will resize to the container automatically if you don't pass `width/height`. In fact, because of default values, the image will behave like that with no parameters other than `files`:

`<rise-image files="image.jpg"></rise-image>`

Thanks!

**Pull request merged**
