### PR TITLE
Encode file path correctly (fix for issue 847)

### PR DESCRIPTION
**Pull request by olegrise**
## Description
- use `encodeURI()` instead of `encodeURIComponent()` in order to encode file path correctly.

**Problem:**
The typical image URL looks like this 
```"risemedialibrary-XYZ/my image.jpg"```
When encoded using `encodeURIComponent()`, the full URL look like this:
```
https://storage.googleapis.com/risemedialibrary-XYZ%2Fmy%20image.jpg
```
This URL is invalid because `/` in the path is replaced by`%2F`, however it work (by accident 😉 ). What happens is that storage.googleapis.com returns 301 redirect to the decoded URL 
````
https://storage.googleapis.com/risemedialibrary-XYZ/my image.jpg
````
and then the redirected call returns the image. 

Here is the problem, when URL includes escaped characters, double decoding removes escaped characters making the file name invalid. First decoding happens on redirects and second when google API parses the URL. Here is an example. Let's say image path is 
```
risemedialibrary-XYZ/folder 1/filename%20with%20space.jpg
```
if encoded with `encodeURIComponent()`, it will become
```
risemedialibrary-XYZ%2Ffolder%201%2Ffilename%20with%2520space.jpg
```
Requesting this from googleapis will result in 301 redirect to 
```
risemedialibrary-XYZ/folder 1/filename%20with%20space.jpg
```
and then googleapis will decode it again and the path becomes invalid because this file does not exist: 
```
risemedialibrary-XYZ/folder 1/filename with space.jpg
```
it should be `filename%20with%20space.jpg` and not `filename with space.jpg`

**Here is how the fix works:**
When `encodeURI()` is used, the encoded URL looks like this;
```
risemedialibrary-XYZ/folder%201/filename%20with%2520space.jpg
```
This is a valid URL path and does not result in 301 redirect. Googleapis decodes it once and gets the correct file path.

## Motivation and Context
Fix for https://github.com/Rise-Vision/rise-launcher-electron/issues/847

## How Has This Been Tested?
Unit tests are updated.
Tested manually in Editor, Rise Vision Anywhere, and Chrome OS Player.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

### CODE REVIEW

**Comment by stulees** [comment]
@olegrise Looks good but could you add some extra test coverage that tests against filenames with special characters? As well as try out manually testing file(s) with special characters? Have a look in Uptime company storage - https://apps.risevision.com/storage?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55 , in the _Special Characters/Images_ folder. You'll see some example files there you can base test coverage and/or manual tests on.

**Comment by olegrise** [comment]
@stulees I had to revise the encoding algorithm because just as you suspected some characters like `?` weren't encoded by `encodeURI()`. The new logic breaks the path into pieces and encodes each piece using `encodeURIComponent`. I tested manually and also added a new unit test that attempts to download a file with all weird characters. Please review. Thanks.

**Comment by stulees** [comment]
@ezequielc FYI, I think you can close PR #66 as this PR will be covering it. Thanks

**Comment by ezequielc** [comment]
@stulees Thanks for the heads up, closed.

**Pull request merged**
