### PR TITLE
Adding PR template

### PR DESCRIPTION
**Pull request by stulees**
@alanclayton @alexey-rise @andrecardoso @alex-deaconu @ezequielc @fjvallarino @olegrise @santiagonoguez @tejohnso As discussed in SoS, this is the PR template for us to now abide by. Please review it, if you think anything is missing or disagree with the format, lets discuss here. Once we're all good with it, the intention is to add this to a bunch of other repos, which @alanclayton has comprised a list of immediate ones to do. Thanks!

### CODE REVIEW

**Comment by stulees** [comment]
@fjvallarino Good question. I think we continue to approve changes as we do, but we only modify the PR main message to apply the `[X]` when we're comfortable with submitter completing checklist. Thoughts?

**Comment by fjvallarino** [comment]
@stulees I agreed that we should keep approving and adding comments as we currently do. I guess we can either:

- Have the Reviewer modify the main message to mark the item themselves
- Add a comment in the PR saying that they completed the process

The second option has the advantage of being explicit in the Reviewer saying they did complete that step (nobody really knows who modified the PR main message)

**Comment by stulees** [comment]
@fjvallarino Good point. I'm good with the reviewer _adding a comment_ option to explicitly state you agree checklist is completed.

**Comment by stulees** [comment]
@fjvallarino Spoke with @alanclayton and made a change to remove the checkboxes and change the wording to be a commitment upon action.

**Comment by fjvallarino** [comment]
@stulees makes sense. Thanks!

**Pull request merged**
